### ISSUE TITLE
Blender 2.8 support

### ISSUE THREAD

**Issue by mr-highball** [castle-engine/cge-blender#1]
Hello,
Attempting to add both castle anim/x3d exporter to latest blender 2.8 fails.
2.8 is still in beta but I was wondering if there were plans to upgrade the scripts for the newer version or if gltf files were going to be primarily used from now on (from the wiki it looks as if only static gltf are supported as of now)

**Comment by michaliskambi** [comment]
1. Our X3D exporter (in CGE on https://castle-engine.io/creating_data_blender.php ) is only a slightly modified version of the original exporter from Blender < 2.8 to X3D. There is a ticket in Blender asking to update that exporter to Blender 2.8: https://developer.blender.org/T59727 , you can subscribe there.

    Unfortunately, no developer yet has volunteered to do this work. I'm sure someone will do it one day (I may do it one day!, but right now I'm overworked :) ). When it happens, the CGE exporter will be upgraded along with it.

    The castle-anim-frames exporter also uses X3D under the hood (internally, castle-anim-frames is just a sequence of X3D models). The castle-anim-frames code is quite small, so upgrading to it Blender 2.8 is probably a breeze -- but it also depends on upgrading the X3D exporter to Blender 2.8.

    So, in short: I'm waiting for some good soul to do the work on the Blender side (upgrading the original Blender X3D exporter to Blender 2.8). I'm sure that someone will do it one day.

2. My plan forward (for CGE) is to extend glTF 2.0 support in Castle Game Engine. It will support animations in February (I already promised that, and I would like to use it for personal projects too :) ), for the beginning the simple animations of transformations/camera (not skin). Later, I also want to add PBR support (across entire Castle Game Engine, so we can support glTF perfectly, and we will also extend X3D specification to include PBR --- my plans about it are on https://github.com/michaliskambi/x3d-tests/wiki/Include-PBR-(PhysicalMaterial-and-related-concepts)-in-the-official-X3D-specification ). And at some point, I'll also implement skin support from glTF (using existing skin support in X3D H-Anim, that already works in CGE).

    Bottom line: my plan forward is to put a lot of effort into supporting glTF as our main interchange format. Khronos has developed great exporter from Blender to glTF, and I want to use it :) So at some point in 2019, it's possible that glTF will become our primary format to "interchange 3D data". Castle Game Engine will keep using X3D as a "scene graph", but X3D nodes can be our internal API, while the interchange format can be glTF, X3D, or a number of other formats.

**Comment by michaliskambi** [comment]
I'm closing this ticket for now, as I don't plan to work on it.

Feel welcome to reopen it, once Blender 2.8 X3D exporter will be ready, or if you want to take this task yourself of course (whether working on Blender side, or working on CGE side). Contributions are welcome :)
